name: Update README

on:
  schedule:
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch:
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        run: |
          export TZ=Asia/Shanghai  
          sed -i "s/最后一次更新时间：.*/最后一次更新时间：$(date '+%Y-%m-%d %H:%M:%S')/" README.md
          git config --local user.email "1004279909@qq.com"
          git config --local user.name "bestruirui"
          git add README.md
          git commit -m "$(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
